version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"          # Expose Nginx on host port 8080
    depends_on:
      - service_1
      - service_2
    # Optional: use volume to mount nginx.conf for live editing
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  service_1:
    build: ./service_1
    container_name: service_1
    expose:
      - "8001"

  service_2:
    build: ./service_2
    container_name: service_2
    expose:
      - "8002"