FROM nginx:latest

# # Remove the default config (optional but recommended for full control)
# RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom nginx.conf into the image
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default Nginx port
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]